# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Home Assistant CUPS Raspberry Pi
slug: rpi-cups
description: CUPS for Home Assistant. Based on olbat/cupsd
url: "https://github.com/leoedin/ha-cups-rpi/cups-rpi"
arch:
  - aarch64
  - armhf
  - armv7
  - amd64
init: false
image: olbat/cupsd
version: latest
host_dbus: true
usb: true
map:
  - "config:rw"
ports:
  631/tcp: 631
ports_description:
  631/tcp: "CUPS web admin port"